permalink: /:title.html
# in the templates via {{ site.myvariable }}.
title: Qiang Hu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Happy Hacking!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Qiang.Hu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  huqiang

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
# Sass
sass:
  style: :compressed
  sass_dir: _sass

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

google_verification: true

